spring.application.name=weddingplanner
spring.datasource.url=jdbc:mysql://localhost:3306/wedding_system
spring.datasource.username=root
spring.datasource.password=L123adeesh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
